---
# tasks file for mysql_db
- name: Install MySQL database
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
  become: yes

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Create Application Database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
  become: yes

- name: Create Application DB User
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    state: present
  become: yes
